version: '3'

services:
  cvscan-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./input:/app/input
      - ./output:/app/output
      - ./cv_dummy:/app/cv_dummy
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]